### PR TITLE
fix: Used different colors for Notifications and episode updates

### PR DESCRIPTION
**Pull request by OlaoluwaM**
There wasn't enough contrast between the pop-up notification and its text when it was green so I made it a light shade of black, but that change caused issues with the podcast notifier, the dot beside an updated podcast. The dot blended with the background color.

However, I was able to separate the colors used for the dot and notification pop up

image

### CODE REVIEW

**Comment by davidbgonz** [comment]
I'm a bit confused with the what was done for the notification dot. Why not just set notification to a different color? Notification handles the color for the dot on the card as well as the podcast page. The podcast episode dot is still grey:
image

**Comment by OlaoluwaM** [comment]
Oh, I must have missed that, but the issue is with the pop-up notification. I have already changed things, so I can't reproduce it right now, but if you can do an action that invokes a pop-up, such as adding a song to the queue while using the original setup, you should see what I mean.

**Comment by OlaoluwaM** [comment]
> I'm a bit confused with the what was done for the notification dot. Why not just set notification to a different color? Notification handles the color for the dot on the card as well as the podcast page. The podcast episode dot is still grey: image
> 
> Is notification in `color.ini` used in more than just the dots?

Could you give me the class names for this dot?

**Comment by davidbgonz** [comment]
Ah okay, I understand now. For the class name, I'm not going to be by a computer for the next 14ish hours. If you get the class name by then ping me in the discord. If not I'll give you the class name here. 

And on the subject of the contrast increase for the dot: we may need to take a look at some of the other color schemes to make sure they're all okay.

**Comment by davidbgonz** [comment]
And for the pop up, is that the one when you're trying to add a song to a playlist when that song already exists there?

**Comment by OlaoluwaM** [comment]
> And for the pop up, is that the one when you're trying to add a song to a playlist when that song already exists there?

This is the pop-up I mean. Try adding a song or playlist to the queue. It was originally green with the text being rosewater and not that visible :(

image

**Comment by davidbgonz** [comment]
Ah! Good catch!

For the CSS selector for the dot, we should use something more generic like:

```
span[aria-label='New episide']                   <= This one is for the dots in the episode lists inside a podcast page
span[aria-label='New Podcast Episode']   <= This one is for the dot inside a podcast episode page
```

The attribute selector alone should be sufficient since we're trying to overwrite a selector that's a single class. If not we can add `.main-view-container` which should be in both the home page and podcast pages. I lost the dot on the Home card I was testing so you would need to grab exactly what that label is then match the format to above (if the label is different). This should cover all the dots.

**Comment by OlaoluwaM** [comment]
Also, we will need to add the `--spice-accent` for other color schemes as well 👀

**Comment by davidbgonz** [comment]
I added a comment on the css file. Once this is resolved I think we're in a good place to merge.

> Also, we will need to add the `--spice-accent` for other color schemes as well

Since you added a fallback variable we should be good for now. To adjust the other color schemes (i.e. green), we can create new issues for them.

**Comment by davidbgonz** [comment]
Hey, sorry for the crazy delay. This looks good now. I make some fixes to the settings page and resolved the merge conflicts for this PR. We are good to go!

**Pull request merged**
